// <auto-generated />
namespace AIUB_Portal_Redesign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RenameProg2Dep : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameProg2Dep));
        
        string IMigrationMetadata.Id
        {
            get { return "202505281734224_RenameProg2Dep"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
